# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discounted', models.BooleanField(default=False)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
