# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171029_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abr', 'Abrigos'), ('Acc', 'Accesorios'), ('Ame', 'Americanas'), ('Bas', 'Basicos'), ('Bot', 'Botas'), ('Cam', 'Camisas'), ('Jer', 'Jerseis'), ('Pan', 'Pantalones'), ('Sud', 'Sudaderas'), ('Vaq', 'Vaqueros'), ('Zap', 'Zapatillas')], max_length=20, null=True),
        ),
    ]
