# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171030_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abr', 'Abrigos'), ('Acc', 'Accesorios'), ('Ame', 'Americanas'), ('Bas', 'Basicos'), ('Bot', 'Botas'), ('Cam', 'Camisas'), ('Jer', 'Jerseis'), ('New', 'Novedades'), ('Ofer', 'Ofertas'), ('Pan', 'Pantalones'), ('Sud', 'Sudaderas'), ('Vaq', 'Vaqueros'), ('Zap', 'Zapatillas')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'men'), ('F', 'women')], max_length=20, null=True),
        ),
    ]
