# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20171030_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abrigos', 'Abrigos'), ('Americanas', 'Americanas'), ('Basicos', 'Basicos'), ('Camisas', 'Camisas'), ('Jerseis', 'Jerseis'), ('Novedades', 'Novedades'), ('Ofertas', 'Ofertas'), ('Pantalones', 'Pantalones'), ('Sudaderas', 'Sudaderas'), ('Vaqueros', 'Vaqueros')], max_length=20, null=True),
        ),
    ]
