# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20171030_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abrigos', 'Abrigos'), ('Chaquetas', 'Chaquetas'), ('Americanas', 'Americanas'), ('Camisetas', 'Camisetas'), ('Camisas', 'Camisas'), ('Jerseis', 'Jerseis'), ('Novedades', 'Novedades'), ('Ofertas', 'Ofertas'), ('Pantalones', 'Pantalones'), ('Sudaderas', 'Sudaderas'), ('Vaqueros', 'Vaqueros')], max_length=20, null=True),
        ),
    ]
