# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20171030_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='footwear',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abrigos', 'Abrigos'), ('Chaquetas', 'Chaquetas'), ('Americanas', 'Americanas'), ('Camisetas', 'Camisetas'), ('Camisas', 'Camisas'), ('Jerseis', 'Jerseis'), ('Pantalones', 'Pantalones'), ('Sudaderas', 'Sudaderas'), ('Zapatos', 'Zapatos'), ('Mocasines', 'Mocasines'), ('Botas', 'Botas'), ('Deportivas', 'Deportivas')], max_length=20, null=True),
        ),
    ]
