# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20171031_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothes',
            field=models.BooleanField(default=True),
        ),
    ]
