# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20171031_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('Novedades', 'Novedades'), ('Ofertas', 'Ofertas'), ('Prendas', 'Prendas'), ('Calzado', 'Calzado'), ('Complementos', 'Complementos')], default='Prendas', max_length=20),
        ),
    ]
