# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20171101_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Abrigos', 'Abrigos'), ('Chaquetas', 'Chaquetas'), ('Vestidos', 'Vestidos'), ('Americanas', 'Americanas'), ('Camisetas', 'Camisetas'), ('Camisas', 'Camisas'), ('Jerseis', 'Jerseis'), ('Pantalones', 'Pantalones'), ('Sudaderas', 'Sudaderas'), ('Zapatos', 'Zapatos'), ('Mocasines', 'Mocasines'), ('Botas', 'Botas'), ('Deportivas', 'Deportivas'), ('Cinturones', 'Cinturones'), ('Bufandas', 'Bufandas'), ('Gorros', 'Gorros'), ('Corbatas', 'Corbatas'), ('Faldas', 'Faldas'), ('Bolsos', 'Bolsos')], max_length=20, null=True),
        ),
    ]
