# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20171109_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity',
        ),
    ]
