# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
            ],
        ),
    ]
