# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_userpaymentmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=80)),
                ('codigo_cvv', models.IntegerField(max_length=3)),
                ('numero_tarjeta', models.IntegerField()),
                ('direccion', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('codigo_postal', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='UserPaymentModel',
            new_name='UserPersonalModel',
        ),
    ]
