# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20171106_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfinancialmodel',
            name='codigo_cvv',
            field=models.IntegerField(),
        ),
    ]
