# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_userorder_total_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='products',
            field=models.ManyToManyField(to='cart.CartProduct'),
        ),
    ]
