# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20171109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
