# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20171109_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userorder',
            name='size',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
