# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20171109_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='size',
        ),
    ]
